info = ['info', 'Shows you some useful information', 'i']
helpcmd = ['help', 'Shows you this message', '?']
invite = ['invite', 'Shows you an invite for Groovy']
support = ['support', 'Shows you an invite to the support server']
shard = ['shard', 'Shows you your current shard id']
stats = ['stats', 'Shows you Groovys current stats']
donate = ['donate', 'Shows you some information about donating']
vote = ['vote', 'Shows you some information about upvoting', 'upvote']
ping = ['ping', 'Groovy? Are you online?']
sponsor = ['sponsor', 'Shows you some information about our sponsor']

play = ['play', 'Lets you play any music you want', 'p, add']
playtop = ['playtop', 'Like play but adds the song to the top', 'addtop, pt']
playskip = ['playskip', 'Like play but adds the song to the top and skips', 'addskip, ps']
join = ['join', 'Tells the bot to join your channel', 'j, summon']
leave = ['leave', 'Tells the bot to leave your channel', 'l, exit, quit']
search = ['search', 'Lets you search songs', 'find']
pause = ['pause', 'Lets you pause the bot']
resume = ['resume', 'Lets you resume the bot']
skip = ['skip', 'Lets you skip the current track', 's']
seek = ['seek', 'Lets you seek to specific positions']
stop = ['stop', 'Lets you stop the bot']
now = ['now', 'Shows you all information about the current track', 'np']
queue = ['queue', 'Shows you each song inside the queue', 'q']
volume = ['volume', 'Lets you change the volume', 'vol']
shuffle = ['shuffle', 'Lets you activate shuffling']
loop = ['loop', 'Lets you activate the loop', 'lp']
loopqueue = ['loopqueue', 'Lets you activate the loopqueue', 'lq']
move = ['move', 'Lets you move a song from one position to another', 'mv']
remove = ['remove', 'Lets you remove a specific song', 'rm']
prefix = ['prefix', 'Lets you change the bots prefix']
setdj = ['setdj', 'Lets you activate/deactivate the dj-mode', 'dj']
control = ['control', 'Lets you control the bot with reactions', 'cp, panel']
clear = ['clear', 'Lets you clear the queue', 'cls, cl']
reset = ['reset', 'Lets you reset the current progress', 'restart']
cleanup = ['cleanup', 'Lets you delete all songs from absent users', 'clean']

info_cogs = [info, helpcmd, invite, support, shard, stats, donate, vote, ping, sponsor]

music_cogs = [play, playtop, playskip, join, leave, search, pause, resume, skip, seek, stop, now, queue, volume,
              shuffle, loop, loopqueue, move, remove, prefix, setdj, control, clear, reset]
